# This is a basic workflow to help you get started with Actions

name: Build & push container image

on:
  # Triggers the workflow on cron schedule
  schedule:
    - cron: '30 7 */7 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registries:
    name: Push Docker image to the registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/caddy
            
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository_owner }}/caddy:latest
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
          
#      - name: Delete old images
#        uses: snok/container-retention-policy@v1
#        with:
#          image-names: caddy
#          cut-off: 24 hours ago UTC
#          keep-at-least: 1
#          account-type: personal
#          token: ${{ secrets.GITHUB_TOKEN }}
          
          
